"""empty message

Revision ID: 37153ab35da5
Revises: None
Create Date: 2016-03-05 00:21:04.701037

"""

# revision identifiers, used by Alembic.
revision = '37153ab35da5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MeasurementType')
    op.add_column('Aspect', sa.Column('calculation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Aspect', 'Calculation', ['calculation_id'], ['id'])
    op.add_column('Measurement', sa.Column('value', sa.Float(), nullable=False))
    op.drop_constraint(None, 'Measurement', type_='foreignkey')
    op.drop_column('Measurement', 'measurement_type_id')
    op.drop_column('Measurement', 'max_balls')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurement', sa.Column('max_balls', sa.FLOAT(), nullable=False))
    op.add_column('Measurement', sa.Column('measurement_type_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Measurement', 'MeasurementType', ['measurement_type_id'], ['id'])
    op.drop_column('Measurement', 'value')
    op.drop_constraint(None, 'Aspect', type_='foreignkey')
    op.drop_column('Aspect', 'calculation_id')
    op.create_table('MeasurementType',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
